Repository arpit456jain/Amazing-Js-Projects, pull requests merged in 2021-08, with the labels that each got.

#76 Snake Game
  Snake Game/index.html
  Snake Game/script.js
  Snake Game/style.css
Labels: DCP21, Level2

#80 Image Filter App
  Image Filter App/index.html
  Image Filter App/preview.png
  Image Filter App/script.js
  Image Filter App/style.css
  style_links.json
Labels: DCP21, Level 3

#86 Creating a stop watch
  StopWatch/index.html
  StopWatch/preview.png
  StopWatch/script.js
  StopWatch/style.css
  style_links.json
Labels: Level 3, DCP21

#90 Improved README
  README.md
Labels: DCP21, Level1

#91 Making fun with Breakout Game
  Breakout Game/index.html
  Breakout Game/preview.png
  Breakout Game/script.js
  Breakout Game/style.css
  style_links.json
Labels: Level 3, DCP21

#92 Double Vertical Slider
  Double Vertical Slider/index.html
  Double Vertical Slider/preview.png
  Double Vertical Slider/script.js
  Double Vertical Slider/style.css
  style_links.json
Labels: Level 3, DCP21

#97 checking palindrome
  Palindrome Check/index.html
  Palindrome Check/preview.png
  Palindrome Check/script.js
  Palindrome Check/style.css
  style_links.json
Labels: Level 3, DCP21
