Repository arpit456jain/Amazing-Js-Projects, pull requests merged in 2021-07, with the labels that each got.

#4 updated readme file
  README.md
Labels: enhancement, good first issue

#15 added height to image
  Magic Image/index.html
Labels: Level1

#22 Weather App
  Weather-App/index.html
  Weather-App/script.js
  Weather-App/style.css
  style_links.json
Labels: level 3

#25 Added Simon Game
  Simon Game/games.js
  Simon Game/index.html
  Simon Game/sounds/blue.mp3
  Simon Game/sounds/green.mp3
  Simon Game/sounds/red.mp3
  Simon Game/sounds/wrong.mp3
  Simon Game/sounds/yellow.mp3
  Simon Game/styles.css
Labels: DCP21, level 3

#27 Add Drum Kit
  Drum Kit/images/crash.png
  Drum Kit/images/kick.png
  Drum Kit/images/snare.png
  Drum Kit/images/tom1.png
  Drum Kit/images/tom2.png
  Drum Kit/images/tom3.png
  Drum Kit/images/tom4.png
  Drum Kit/index.html
  Drum Kit/index.js
  Drum Kit/sounds/crash.mp3
  Drum Kit/sounds/kick-bass.mp3
  Drum Kit/sounds/snare.mp3
  Drum Kit/sounds/tom-1.mp3
  Drum Kit/sounds/tom-2.mp3
  Drum Kit/sounds/tom-3.mp3
  Drum Kit/sounds/tom-4.mp3
  Drum Kit/styles.css
Labels: DCP21, Level2

#28 Added Memory Game
  Memory Game/assets/images/Favicons/favicon.ico
  Memory Game/assets/images/burger.png
  Memory Game/assets/images/donut.png
  Memory Game/assets/images/fried-chicken.png
  Memory Game/assets/images/ice-cream.png
  Memory Game/assets/images/milkshake.png
  Memory Game/assets/images/muffin.png
  Memory Game/assets/images/noodles.png
  Memory Game/assets/images/pizza.png
  Memory Game/assets/sounds/correct.wav
  Memory Game/assets/sounds/game-over.wav
  Memory Game/assets/sounds/wrong.wav
  Memory Game/css/styles.css
  Memory Game/index.html
  Memory Game/js/app.js
  style_links.json
Labels: DCP21, Level 3

#30 AddedClock
  Clock/Clock.png
  Clock/index.html
  Clock/index.js
  Clock/style.css
Labels: DCP21

#31 Add Contributing guidelines
  CONTRIBUTORS.md
Labels: DCP21, Level1

#34 add points table in read me
  README.md
Labels: DCP21, Level1

#38 Added Missing Projects
  style_links.json
Labels: DCP21, Level1

#39 Added Connect Four Game
  Connect Four/css/styles.css
  Connect Four/index.html
  Connect Four/js/index.js
  style_links.json
Labels: DCP21, Level 3

#40 Added GitHub pages website link to Readme
  README.md
Labels: DCP21, Level0

#43 Corrected the Issue Template
  .github/ISSUE_TEMPLATE/Bug_Feature_Docs.md
Labels: DCP21, Level0

#48 Added Issue Tracker
  Issue Tracker/index.html
  Issue Tracker/script.js
  Issue Tracker/style.css
Labels: DCP21, Level 3

#49 Added Password Generator
  Password Generator/index.html
  Password Generator/script.js
  Password Generator/style.css
  style_links.json
Labels: DCP21, Level 3

#51 Added Birthday Countdown
  Birthday Countdown/index.html
  Birthday Countdown/script.js
  Birthday Countdown/style.css
  style_links.json
Labels: DCP21, Level 3

#53 adding KeyBoard project with light and dark theme
  Keyboard/index.html
  Keyboard/keyboard.ico
  Keyboard/moon.png
  Keyboard/script.js
  Keyboard/style.css
  Keyboard/sun.png
  style_links.json
Labels: DCP21, Level 3

#54 Tip Calculator
  Tip Calculator/index.html
  Tip Calculator/style.css
  Tip Calculator/style.js
Labels: DCP21, Level 3

#55 Update Home Page UI
  Analog clock/preview.png
  Birthday Countdown/preview.png
  Clock And Alarm/preview.png
  Clock/preview.png
  Connect Four/preview.png
  Drag N Drop/preview.png
  Drum Kit/preview.png
  Issue Tracker/preview.png
  Keyboard/preview.png
  Magic Color/preview.png
  Magic Image/preview.png
  Memory Game/preview.png
  Password Generator/preview.png
  Simon Game/preview.png
  Tic Tac Toe/preview.png
  Tic-Tac-Toe with computer/preview.png
  To-Do List/preview.png
  Weather-App/preview.png
  index.html
  script.js
  style.css
Labels: DCP21, Level 3

#58 Added back to top
  index.html
  script.js
  style.css
Labels: DCP21, Level2

#59 some images are not rendering on home page
  style_links.json
Labels: DCP21, Level2

#67 Custom Range Slider
  Custom Range Slider/index.html
  Custom Range Slider/preview.png
  Custom Range Slider/script.js
  Custom Range Slider/style.css
  style_links.json
Labels: DCP21, Level 3

#72 Added Missing Project and Preview
  Tip Calculator/preview.png
  style_links.json
Labels: DCP21, Level2, Urgent

#73 Snake Game
  Snake Game/images/apple1.png
  Snake Game/images/mango.png
  Snake Game/images/pear.png
  Snake Game/images/wp2409705.jpg
  Snake Game/index.html
  Snake Game/preview.png
  Snake Game/script.js
  Snake Game/style.css
  style_links.json
Labels: DCP21, Level 3
