Repository arpit456jain/Amazing-Js-Projects, pull requests merged in 2022-04, with the labels that each got.

#460 Add game of pong
  Game-of-pong/CSS/style.css
  Game-of-pong/JS/script.js
  Game-of-pong/Readme.md
  Game-of-pong/index.html
  style_links.json
Labels: GSSoC22, ready to merge

#494 Added Instagram Mini
  InstagramMini/272906367_471067674682932_5387380735934833246_n.mp4
  InstagramMini/273470311_678773606827659_2545209592104638155_n.mp4
  InstagramMini/273884287_1162311734577078_3652211896240796441_n.mp4
  InstagramMini/274006084_161179402932069_5607339682707444194_n.mp4
  InstagramMini/Filter.css
  InstagramMini/README.txt
  InstagramMini/Reel.css
  InstagramMini/Screenshot (77).png
  InstagramMini/back.png
  InstagramMini/chat.png
  InstagramMini/gradienta-LeG68PrXA6Y-unsplash.jpg
  InstagramMini/heart(1).png
  InstagramMini/heart(2).png
  InstagramMini/heart.png
  InstagramMini/home.png
  InstagramMini/index.html
  InstagramMini/instagram-font-png-1.png
  InstagramMini/instagram_wordmark_logo_icon_169660.png
  InstagramMini/logo-ig-png-32464.png
  InstagramMini/luke-chesser-zFaSM1hz02c-unsplash.jpg
  InstagramMini/milad-fakurian-nY14Fs8pxT8-unsplash.jpg
  InstagramMini/musical-note.png
  InstagramMini/outline_close_white_24dp.png
  InstagramMini/outline_flash_on_white_24dp.png
  InstagramMini/outline_flip_camera_ios_white_36dp.png
  InstagramMini/outline_location_on_white_24dp.png
  InstagramMini/outline_settings_white_24dp.png
  InstagramMini/plus.png
  InstagramMini/previous.png
  InstagramMini/script.js
  InstagramMini/search_black_24dp (1).svg
  InstagramMini/send (1).png
  InstagramMini/send.png
  InstagramMini/style.css
  InstagramMini/three-dots.png
  style_links.json
Labels: Level2

#490 Emoji Slider in Js.
  custom Emoji slider/ img/1 (1).png
  custom Emoji slider/ img/2.png
  custom Emoji slider/ img/3.png
  custom Emoji slider/ img/4.png
  custom Emoji slider/ img/5.png
  custom Emoji slider/index.html
  custom Emoji slider/script.js
  custom Emoji slider/style.css
Labels: Level2, GSSoC22

#501 Hangman Game
  Hangman Game/index.html
  Hangman Game/readme.md
  style_links.json
Labels: Level3, GSSoC22

#520 Added Sum of Digits
  Sum Of Digits Caluclator/bgi.png
  Sum Of Digits Caluclator/readme
  Sum Of Digits Caluclator/sum.css
  Sum Of Digits Caluclator/sum.html
  Sum Of Digits Caluclator/sum.js
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#521 Adding random wave project
  Random Wave/index.html
  Random Wave/script.js
  Random Wave/style.css
  Random Wave/style_links.json
Labels: Level1, GSSoC22, ready to merge

#526 15 puzzle Challenge added
  15-Puzzle-Challenge/15puzzle.css
  15-Puzzle-Challenge/15puzzle.js
  15-Puzzle-Challenge/README.md
  15-Puzzle-Challenge/index.html
  15-Puzzle-Challenge/preview.png
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#535 Added Todo app
  ToDo App/css/style.css
  ToDo App/index.html
  ToDo App/js/index.js
Labels: Level2, GSSoC22, ready to merge

#537 Added file in workflow
  .github/workflows/pr-open-labeler.yml
Labels: GSSoC22, ready to merge

#539 Added the project
  Digital_Clock/README.md
  Digital_Clock/assets/Digital-clock-demo.gif
  Digital_Clock/index.html
  Digital_Clock/index.js
  Digital_Clock/preview.jpg
  Digital_Clock/style.css
Labels: Level2, GSSoC22

#558 Fixed underweight color issue.
  BMI-Calculator/main.js
Labels: GSSoC22, Level0

#564 Delete pr-open-labeler.yml
  .github/workflows/pr-open-labeler.yml
Labels: GSSoC22

#565 Update README.md and testing bot
  README.md
Labels: GSSoC22

#550 Added Reflex Training Game
  Reflex Training/Index.html
  Reflex Training/Reflex.js
  Reflex Training/Styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#545 Snake
  2D Snake Game/README.md
  2D Snake Game/index.html
  2D Snake Game/preview.jpg
  2D Snake Game/script.js
  2D Snake Game/style.css
Labels: Level3, GSSoC22

#556 Update main.js
  BMI-Calculator/main.js
Labels: GSSoC22, changes requested
