Repository arpit456jain/Amazing-Js-Projects, pull requests merged in 2022-03, with the labels that each got.

#167 Added interesting features to the analog clock project
  .DS_Store
  Analog clock/.DS_Store
  Analog clock/Previews/.DS_Store
  Analog clock/Previews/Preview1.png
  Analog clock/Previews/Preview2.png
  Analog clock/Previews/Preview3.png
  Analog clock/Previews/Preview4.png
  Analog clock/Previews/Preview5.png
  Analog clock/Previews/README.txt
  Analog clock/Sounds/.DS_Store
  Analog clock/Sounds/Alarm.mp3
  Analog clock/Sounds/Click.mp3
  Analog clock/Sounds/clock.mp3
  Analog clock/index.html
  Analog clock/main.css
  Analog clock/main.js
Labels: Level2

#172 Added Music Website
  Music/README.md
  Music/bensound-clearday.mp3
  Music/images/README.md
  Music/images/WhatsApp Image 2022-03-01 at 8.58.34 PM.jpeg
  Music/images/image.jpeg
  Music/images/pause.png
  Music/images/play.png
  Music/index.html
  Music/style.css
Labels: Level2

#177 Added Convert Font WebApp
  Convert Fonts/Font/ritikstylus-regular.woff
  Convert Fonts/Font/ritikstylus-regular.woff2
  Convert Fonts/Font/stylesheet.css
  Convert Fonts/index.html
  Convert Fonts/js/app.js
Labels: Level2

#180 Added BMI Calculator
  BMI-Calculator/index.css
  BMI-Calculator/index.html
  BMI-Calculator/main.js
Labels: Level2

#205 Added new Note taking app
  Note Taking App/assets/favicon.png
  Note Taking App/index.html
  Note Taking App/main.js
  Note Taking App/style.css
Labels: Level2

#204 Optimized Palindrome Check
  Palindrome Check/script.js
Labels: Level1

#202 Added Blurry Loading
  Blury Loading Page/index.css
  Blury Loading Page/index.html
  Blury Loading Page/index.js
Labels: Level1

#199 #195 Fixed image not showing.
  .vscode/settings.json
  Bubble Burst Game/.DS_Store
  Bubble Burst Game/index.html
  Bubble Burst Game/preview.png
  Bubble Burst Game/script.js
  Bubble Burst Game/style.css
  Bubble-Burst-Game/preview.png
  Lorem Ipsum Generator/app.js
  Lorem Ipsum Generator/index.html
  Lorem Ipsum Generator/logo.svg
  Lorem Ipsum Generator/preview.png
  Lorem Ipsum Generator/styles.css
  Lorem Ipsum/preview.png
  Quote Generator/preview.png
Labels: Level1

#198 added photo editor project
  Photo-Editor/image-editor.css
  Photo-Editor/index.html
  Photo-Editor/logo.png
  Photo-Editor/preview.PNG
  Photo-Editor/sample.jpg
  Photo-Editor/script.js
  Photo-Editor/style.css
Labels: Level3

#197 Added NotesMaker App
  Notes Maker/index.html
  Notes Maker/script.js
  Notes Maker/style.css
Labels: Level2

#192 I am a GSSOC participant . I have added new project : color guessing game
  color-guessing game/index.html
  color-guessing game/java/main.js
  color-guessing game/styles.css
Labels: Level2

#183 added navbar to the website
  .vscode/settings.json
  index.html
  logo1.png
  style.css
Labels: Level1, GSSoC22, ready to merge

#212 i add new js project Fresh Quotes 2
  Fresh Quotes/index.html
  Fresh Quotes/style.css
Labels: Level2, GSSoC22, ready to merge

#224 added text to speech converter
  Text_to_speech_converter/index.html
  Text_to_speech_converter/main.js
  Text_to_speech_converter/styles.css
Labels: Level3, GSSoC22, ready to merge

#228 Candy Crush files added
  Candy Crush Clone/candy-crush-background.png
  Candy Crush Clone/images/blue-candy.png
  Candy Crush Clone/images/green-candy.png
  Candy Crush Clone/images/orange-candy.png
  Candy Crush Clone/images/purple-candy.png
  Candy Crush Clone/images/red-candy.png
  Candy Crush Clone/images/yellow-candy.png
  Candy Crush Clone/index.html
  Candy Crush Clone/script.js
  Candy Crush Clone/styles.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#230 Added Random-joke-generator
  Random-joke-generator/README.md
  Random-joke-generator/demo.mp4
  Random-joke-generator/index.html
  Random-joke-generator/style.css
  Random-joke-generator/working.js
Labels: Level2, GSSoC22, ready to merge

#232 Added Age Calculator
  Age Calculator/index.html
  Age Calculator/script.js
  Age Calculator/style.css
Labels: Level2, GSSoC22, ready to merge

#233 [GSSoC'22 Contributor] : Added My Password Generator and New Year Countdown Projects
  Happy New Year CountDown Timer/README.md
  Happy New Year CountDown Timer/images/flower-background.webp
  Happy New Year CountDown Timer/images/happy-new-year-icon.jpg
  Happy New Year CountDown Timer/index.html
  Happy New Year CountDown Timer/script.js
  Happy New Year CountDown Timer/style.css
  Password Generator/README.md
  Password Generator/images/digital.webp
  Password Generator/index.html
  Password Generator/script.js
  Password Generator/style.css
Labels: Level3, GSSoC22, ready to merge

#235 fixed missing after clicked effects and also added sound effects.
  Calculators/Neuromorphic Calculator/btn-sound.wav
  Calculators/Neuromorphic Calculator/index.html
  Calculators/Neuromorphic Calculator/style.css
Labels: Level1, GSSoC22, ready to merge

#254 Footer added
  index.html
  style.css
Labels: Level1, GSSoC22, ready to merge

#245 Dice Game with a working button.
  DIce Game Updated/dicee.html
  DIce Game Updated/images/dice1.png
  DIce Game Updated/images/dice2.png
  DIce Game Updated/images/dice3.png
  DIce Game Updated/images/dice4.png
  DIce Game Updated/images/dice5.png
  DIce Game Updated/images/dice6.png
  DIce Game Updated/index.js
  DIce Game Updated/styles.css
Labels: Level2, GSSoC22, ready to merge

#256 Update hover effect in Navbar
  style.css
Labels: invalid

#229 Dictionary App files added
  Dictionary App/index.html
  Dictionary App/script.js
  Dictionary App/styles.css
  style_links.json
Labels: Level2, GSSoC22

#260 updated README.md (#1)
  README.md
Labels: Level0

#263 jokes chrome extension added
  Jokes Chrome Extension/manifest.json
  Jokes Chrome Extension/output_ss.PNG
  Jokes Chrome Extension/popup.html
  Jokes Chrome Extension/script.js
  Jokes Chrome Extension/sloth.png
  Jokes Chrome Extension/style.css
Labels: Level2

#262 Added Random String Generator Project
  String Generator/index.html
  String Generator/main.js
  String Generator/preview.png
  String Generator/style.css
Labels: Level2

#269 Ball-Game
  Ball-Game/css.css
  Ball-Game/game/bg.jpeg
  Ball-Game/game/bg.png
  Ball-Game/game/pic.jpg
  Ball-Game/game/pic.png
  Ball-Game/game/pic2.png
  Ball-Game/game/picpg.jpg
  Ball-Game/game/stump.jpg
  Ball-Game/index.html
  Ball-Game/js.js
  style_links.json
Labels: Level3

#267 Sneaker Site files added
  Sneaker Site/img/air.png
  Sneaker Site/img/air2.png
  Sneaker Site/img/blazer.png
  Sneaker Site/img/blazer2.png
  Sneaker Site/img/contact.png
  Sneaker Site/img/crater.png
  Sneaker Site/img/crater2.png
  Sneaker Site/img/facebook.png
  Sneaker Site/img/gift.png
  Sneaker Site/img/hippie.png
  Sneaker Site/img/hippie2.png
  Sneaker Site/img/instagram.png
  Sneaker Site/img/jordan.png
  Sneaker Site/img/jordan2.png
  Sneaker Site/img/master.png
  Sneaker Site/img/return.png
  Sneaker Site/img/search.png
  Sneaker Site/img/shipping.png
  Sneaker Site/img/sneakers.png
  Sneaker Site/img/twitter.png
  Sneaker Site/img/visa.png
  Sneaker Site/img/whatsapp.png
  Sneaker Site/index.html
  Sneaker Site/script.js
  Sneaker Site/styles.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#270 Sudoku Game:Suggest any improvements/changes
  javascript-sudoku-main/app.css
  javascript-sudoku-main/index.html
  javascript-sudoku-main/static/images/icon.jpg
  javascript-sudoku-main/static/js/app.js
  javascript-sudoku-main/static/js/constant.js
  javascript-sudoku-main/static/js/sudoku.js
Labels: Level3, GSSoC22

#271 Resolved CDN issue that was distorting whole WebPage
  index.html
  style.css
Labels: GSSoC22

#272 Currency Convertor Project Added
  Currency Convertor/index.html
  Currency Convertor/preview.png
  Currency Convertor/script.js
  Currency Convertor/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#285 Completed the issue #276 under GSSoC 22
  Digital-clock/README.md
  Digital-clock/clock.html
  Digital-clock/clock.jpg
  Digital-clock/style.css
Labels: Level2, GSSoC22, ready to merge

#289 Added BaseX Calculator files
  BaseX_Calculator/app.js
  BaseX_Calculator/index.html
  BaseX_Calculator/readme.md
  BaseX_Calculator/style.css
Labels: Level2, GSSoC22, ready to merge

#291 Added Guess The Number game
  Guess-The-Number/audio/music.wav
  Guess-The-Number/images/game.svg
  Guess-The-Number/index.html
  Guess-The-Number/index.js
  Guess-The-Number/style.css
Labels: Level2, GSSoC22, ready to merge

#298 Add expense tracker by yashi khare
  Expense-Tracker/Screenshot (28).png
  Expense-Tracker/Screenshot (29).png
  Expense-Tracker/index.html
  Expense-Tracker/readme.md
  Expense-Tracker/script.js
  Expense-Tracker/styles.css
Labels: Level2, GSSoC22, ready to merge

#300 Updated typo "fliter-btn" in index.html file
  Image Filter App/index.html
Labels: Level1

#304 Random shapes and backgrounds
  Random Shapes and Backgrounds/images/gr1.png
  Random Shapes and Backgrounds/images/gr10.png
  Random Shapes and Backgrounds/images/gr11.png
  Random Shapes and Backgrounds/images/gr12.jpg
  Random Shapes and Backgrounds/images/gr13.jpg
  Random Shapes and Backgrounds/images/gr2.png
  Random Shapes and Backgrounds/images/gr3.png
  Random Shapes and Backgrounds/images/gr4.png
  Random Shapes and Backgrounds/images/gr5.jpg
  Random Shapes and Backgrounds/images/gr6.png
  Random Shapes and Backgrounds/images/gr7.png
  Random Shapes and Backgrounds/images/gr8.png
  Random Shapes and Backgrounds/images/gr9.jpg
  Random Shapes and Backgrounds/index.html
  Random Shapes and Backgrounds/index.js
  Random Shapes and Backgrounds/preview.png
  Random Shapes and Backgrounds/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#307 Adding the scrollbar
  style.css
Labels: Level1, GSSoC22, ready to merge

#315 birthday-countdown-bug #316
  Birthday Countdown/script.js
  Birthday Countdown/style.css
Labels: Level1, GSSoC22, ready to merge

#306 Add Guess the Number
  Guess the Number/README.md
  Guess the Number/game.css
  Guess the Number/game.html
  Guess the Number/game.js
  Guess the Number/videos/guess the number.gif
Labels: Level2, GSSoC22

#312 Added Ping Pong Ball Score Keeper
  PIng _Pong _Ball _Score_Keeper/app.js
  PIng _Pong _Ball _Score_Keeper/index.html
  PIng _Pong _Ball _Score_Keeper/style.css
Labels: GSSoC22, changes requested

#326 Prime Factor Calculator using Sieve of Eratosthenes
  Prime Factor Calculator/index.html
  Prime Factor Calculator/preview.png
  Prime Factor Calculator/script.js
  Prime Factor Calculator/style.css
Labels: Level3, GSSoC22, ready to merge

#334 2048 game
  2048_game/README.md
  2048_game/index.html
  2048_game/script.js
  2048_game/styles.css
Labels: Level2, GSSoC22, ready to merge

#319 Added Dice Game
  Dice Game/dicee.html
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/index.js
  Dice Game/styles.css
Labels: Level2, GSSoC22, ready to merge

#336 Transpose of 3X3 Matrix Calculator #328
  Transpose-3X3-Matrix Calculator/README.md
  Transpose-3X3-Matrix Calculator/index.html
  Transpose-3X3-Matrix Calculator/script.js
  Transpose-3X3-Matrix Calculator/style.css
Labels: Level3

#320 Color-Change
  color-change/app.js
  color-change/index.html
  color-change/styles.css
Labels: Level2, GSSoC22, ready to merge

#339 Added Fruit Slice Game
  Fruit Slice Game/Fruit Preview.PNG
  Fruit Slice Game/Images/apple.png
  Fruit Slice Game/Images/grapes.png
  Fruit Slice Game/Images/guava.png
  Fruit Slice Game/Images/heart.png
  Fruit Slice Game/Images/mango.png
  Fruit Slice Game/Song/116344153-squash-large-fruit-hit-chop-sl.m4a
  Fruit Slice Game/index.html
  Fruit Slice Game/script.js
  Fruit Slice Game/style.css
Labels: Level3

#352 Pokemon Generator files added
  Pokemon-Generator/index.html
  Pokemon-Generator/script.js
  Pokemon-Generator/style.css
  style_links.json
Labels: Level2, GSSoC22

#322 Meme Generator
  Meme Generator/README.md
  Meme Generator/index.html
  Meme Generator/script.js
  Meme Generator/style.css
Labels: Level2, GSSoC22, ready to merge

#321 Added Image-Resizer Website/App
  Image-Resizer/README.md
  Image-Resizer/index.html
  Image-Resizer/scripts.js
  Image-Resizer/style.css
Labels: Level2, GSSoC22, ready to merge

#318 Added ColorCode Converter project files
  Color_Code_Converter/app.js
  Color_Code_Converter/index.html
  Color_Code_Converter/readme.md
  Color_Code_Converter/style.css
Labels: Level2

#340 background-Changer-Modification
  Background Color Changer/index.html
  Background Color Changer/script.js
  Background Color Changer/style.css
Labels: Level2, GSSoC22

#353 added my Random Anime profile pic generator to the list...
  Anime random profle  pics/index.html
  Anime random profle  pics/script.js
  Anime random profle  pics/style.css
Labels: Level2, GSSoC22

#351 #347 issue fixed
  Flipbook/README.md
  Flipbook/index.html
  Flipbook/script.js
  Flipbook/style.css
  Flipbook/turn.js
Labels: Level2, GSSoC22

#387 Whack a mole game-fixes #287 issue
  Whack A Mole/assets/dirt.svg
  Whack A Mole/assets/hammer.png
  Whack A Mole/assets/hammerdown.png
  Whack A Mole/assets/mole.svg
  Whack A Mole/index.html
  Whack A Mole/style.css
Labels: Level3, GSSoC22

#361 Gradient background Generator Project Added
  Gradient_Background_Generator/README.md
  Gradient_Background_Generator/index.html
  Gradient_Background_Generator/script.js
  Gradient_Background_Generator/style.css
Labels: Level2, GSSoC22, ready to merge

#364 Readme updated
  README.md
Labels: GSSoC22, ready to merge

#384 Added piano as per #382
  piano/index.html
  piano/notes/A.mp3
  piano/notes/Ab.mp3
  piano/notes/B.mp3
  piano/notes/Bb.mp3
  piano/notes/C.mp3
  piano/notes/D.mp3
  piano/notes/Db.mp3
  piano/notes/E.mp3
  piano/notes/Eb.mp3
  piano/notes/F.mp3
  piano/notes/G.mp3
  piano/notes/Gb.mp3
  piano/script.js
  piano/style.css
Labels: GSSoC22, changes requested

#378 Added changes to the file to sort projects
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#394 Added SearchBar, Responsiveness and changed UI of cards components
  index.html
  script.js
  style.css
Labels: Level3

#372 Added URL Shortner project
  URL-Shortner/CSS/_basic.scss
  URL-Shortner/CSS/_mediaq.scss
  URL-Shortner/CSS/style.css
  URL-Shortner/CSS/style.css.map
  URL-Shortner/CSS/style.scss
  URL-Shortner/app.js
  URL-Shortner/images/bg-boost-desktop.svg
  URL-Shortner/images/bg-boost-mobile.svg
  URL-Shortner/images/bg-shorten-desktop.svg
  URL-Shortner/images/bg-shorten-mobile.svg
  URL-Shortner/images/favicon-32x32.png
  URL-Shortner/images/icon-brand-recognition.svg
  URL-Shortner/images/icon-detailed-records.svg
  URL-Shortner/images/icon-facebook.svg
  URL-Shortner/images/icon-fully-customizable.svg
  URL-Shortner/images/icon-instagram.svg
  URL-Shortner/images/icon-pinterest.svg
  URL-Shortner/images/icon-twitter.svg
  URL-Shortner/images/illustration-working.svg
  URL-Shortner/images/logo.svg
  URL-Shortner/index.html
  URL-Shortner/preview.png
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#373 Number system convertor
  number_system_convertor/numbersystem.css
  number_system_convertor/numbersystem.js
  number_system_convertor/numbersysystem.html
Labels: Level2, GSSoC22

#404 400 issue fixed
  README.md
Labels: GSSoC22, ready to merge

#397 Captcha Generator
  Captcha Generator/captcha.jpg
  Captcha Generator/index.html
  Captcha Generator/preview.png
  Captcha Generator/script.js
  Captcha Generator/styles.css
  color-guessing game/java/main.js
Labels: Level3, GSSoC22, ready to merge

#406 Added a project which uses vanilla javascript to create a type writing effect in a webpage.
  Typewriter effect/app.js
  Typewriter effect/index.html
  Typewriter effect/style.css
Labels: Level1, GSSoC22

#411 new Design plus Features
  calculatorspage.html
  calculatorspage.js
  index.html
  script.js
  style.css
Labels: Level3, GSSoC22, ready to merge

#393 Added 3rd degree equation solver files
  Third_Degree_Equation_Solver/assets/css/bootstrap.css
  Third_Degree_Equation_Solver/assets/css/bootstrap.css.map
  Third_Degree_Equation_Solver/assets/css/style.css
  Third_Degree_Equation_Solver/index.html
  Third_Degree_Equation_Solver/readme.md
  Third_Degree_Equation_Solver/scripts/app.js
  Third_Degree_Equation_Solver/scripts/bootstrap.bundle.js
  Third_Degree_Equation_Solver/scripts/bootstrap.bundle.js.map
Labels: Level2, GSSoC22, ready to merge

#431 Added function grapher files
  Function_Grapher/assets/css/bootstrap.css
  Function_Grapher/assets/css/bootstrap.css.map
  Function_Grapher/assets/css/style.css
  Function_Grapher/index.html
  Function_Grapher/readme.md
  Function_Grapher/scripts/app.js
  Function_Grapher/scripts/bootstrap.bundle.js
  Function_Grapher/scripts/bootstrap.bundle.js.map
  Function_Grapher/scripts/function_plot.js
Labels: Level3, GSSoC22, ready to merge

#412 Added Live user filter
  Live User Filter/index.html
  Live User Filter/script.js
  Live User Filter/style.css
  style_links.json
Labels: Level2, GSSoC22

#427 Shooter game
  2dShooterGame/README.md
  2dShooterGame/assets/alien.png
  2dShooterGame/assets/arme.png
  2dShooterGame/assets/dio.png
  2dShooterGame/assets/dioexpl.png
  2dShooterGame/assets/diohit.mp3
  2dShooterGame/assets/dioknife.png
  2dShooterGame/assets/diotp.png
  2dShooterGame/assets/energy.png
  2dShooterGame/assets/explosion.mp3
  2dShooterGame/assets/explosion.png
  2dShooterGame/assets/feu.png
  2dShooterGame/assets/fireball.png
  2dShooterGame/assets/fond.mp3
  2dShooterGame/assets/fond.png
  2dShooterGame/assets/fond2.png
  2dShooterGame/assets/fond3.png
  2dShooterGame/assets/fond4.png
  2dShooterGame/assets/healthbar.png
  2dShooterGame/assets/kamehameha.png
  2dShooterGame/assets/knife.png
  2dShooterGame/assets/konodio.mp3
  2dShooterGame/assets/konodio.png
  2dShooterGame/assets/laser.mp3
  2dShooterGame/assets/loose.png
  2dShooterGame/assets/muda.png
  2dShooterGame/assets/perso.png
  2dShooterGame/assets/perso2.png
  2dShooterGame/assets/portal.png
  2dShooterGame/assets/readme.png
  2dShooterGame/assets/roadroller.png
  2dShooterGame/assets/roadrollerda.mp3
  2dShooterGame/assets/roadrollersummon.png
  2dShooterGame/assets/robot.png
  2dShooterGame/assets/sniper.png
  2dShooterGame/assets/start.png
  2dShooterGame/assets/summon.mp3
  2dShooterGame/assets/summon.png
  2dShooterGame/assets/teleportation.png
  2dShooterGame/assets/teleportation2.png
  2dShooterGame/assets/tir.png
  2dShooterGame/assets/tir2.png
  2dShooterGame/assets/win.png
  2dShooterGame/assets/zawarudo.mp3
  2dShooterGame/assets/zawarudo.png
  2dShooterGame/index.html
  2dShooterGame/js/perso.js
  2dShooterGame/js/prg.js
  2dShooterGame/js/sprite.js
  2dShooterGame/js/tir.js
  style_links.json
Labels: Level3, GSSoC22, changes requested

#447 Added Project "Fortune Cookie Generator"
  Fortune Cookie Generator/Images/cookie.png
  Fortune Cookie Generator/fortune.js
  Fortune Cookie Generator/index.html
  Fortune Cookie Generator/preview.png
  Fortune Cookie Generator/style.css
Labels: GSSoC22, ready to merge

#443 Adding a Game Typer
  Typer/README.md
  Typer/canvas.js
  Typer/index.html
  Typer/particle.js
  Typer/play.png
  Typer/typer.css
  Typer/typer.js
Labels: Level2, GSSoC22, ready to merge

#441 #368 - Alarm Clock
  Alarm_Clock/index.html
Labels: Level2, GSSoC22, ready to merge
