Repository arpit456jain/Amazing-Js-Projects, pull requests merged in 2022-05, with the labels that each got.

#567 Update typer.css
  Typer/typer.css
Labels: Level1, GSSoC22, ready to merge

#553 Spotify clone added
  SpotifyClone/bg.jpg
  SpotifyClone/covers/1.jpg
  SpotifyClone/covers/10.jpg
  SpotifyClone/covers/2.jpg
  SpotifyClone/covers/3.jpg
  SpotifyClone/covers/4.jpg
  SpotifyClone/covers/5.jpg
  SpotifyClone/covers/6.jpg
  SpotifyClone/covers/7.jpg
  SpotifyClone/covers/8.jpg
  SpotifyClone/covers/9.jpg
  SpotifyClone/index.html
  SpotifyClone/logo.png
  SpotifyClone/playing.gif
  SpotifyClone/script.js
  SpotifyClone/style.css
  style_links.json
Labels: Level2, GSSoC22

#568 Tictactoe
  Tic-Tac-Toe with 2 player/README.md
  Tic-Tac-Toe with 2 player/index.html
  Tic-Tac-Toe with 2 player/project.jpg
  Tic-Tac-Toe with 2 player/script.js
  Tic-Tac-Toe with 2 player/style.css
Labels: Level2, GSSoC22

#582 Leap year modification
  Leap Year/index.html
  Leap Year/style.css
Labels: Level1, GSSoC22

#585 Lyricz... API implemented website
  Lyricz API lyrics finder/index.css
  Lyricz API lyrics finder/index.html
  Lyricz API lyrics finder/index.js
  style_links.json
Labels: GSSoC22, ready to merge

#603 Pong game bug
  Pong game/index.html
Labels: Level1, GSSoC22, ready to merge

#587 resume builder added #576
  Resume-Builder/ReadMe.md
  Resume-Builder/css/style.css
  Resume-Builder/index.html
  Resume-Builder/js/script.js
  Resume-Builder/preview.png
  Resume-Builder/preview/input.png
  Resume-Builder/preview/preview.png
  Resume-Builder/preview/print-preview.png
  Resume-Builder/preview/responsive1.png
  Resume-Builder/preview/responsive2.png
  style_links.json
Labels: GSSoC22, ready to merge

#523 Certificate Generator added
  Certificate Generator/FileSaver.js
  Certificate Generator/Sanchez-Regular.ttf
  Certificate Generator/img/certificate.png
  Certificate Generator/img/temp1.JPG
  Certificate Generator/img/temp2.JPG
  Certificate Generator/index.html
  Certificate Generator/index.js
  Certificate Generator/style.css
  Certificate Generator/template1.pdf
  Certificate Generator/template2.pdf
  style_links.json
Labels: question, Level3, GSSoC22, changes requested

#596 Spy number checker
  Spy Number Checker/bgi.png
  Spy Number Checker/index.html
  Spy Number Checker/readme.md
  Spy Number Checker/spy.css
  Spy Number Checker/spy.js
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#605 Added Special number checker
  Special number checker/bgi.png
  Special number checker/index.html
  Special number checker/readme.md
  Special number checker/special.css
  Special number checker/special.js
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#606 Age Calculator presentation issue resolved
  Age Calculator/index.html
  Age Calculator/style.css
Labels: GSSoC22, ready to merge

#607 Added Favicon in calculator page and main page
  calculatorspage.html
  index.html
  web_favicon.ico
Labels: Level1, GSSoC22, ready to merge

#586 Voice To Text Converter
  Voice To Text Converter/README.md
  Voice To Text Converter/index.html
  Voice To Text Converter/preview.png
  Voice To Text Converter/script.js
  Voice To Text Converter/style.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#620 Eyesightcheck
  EyeSight Check/index.html
  EyeSight Check/preview.jpg
  EyeSight Check/readme.md
  EyeSight Check/script.js
  EyeSight Check/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#630 Carcolorchange
  Car Color Change/index.html
  Car Color Change/preview.jpg
  Car Color Change/script.js
  Car Color Change/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#643 todo-app-edit functionality
  ToDo App/Review.png
  ToDo App/css/style.css
  ToDo App/index.html
  ToDo App/js/index.js
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#645 Fixes broken links and images
  Car Color Change/preview.jpg
  Car Color Change/preview.png
  Certificate Generator/preview.png
  EyeSight Check/preview.png
  Happy number checker/preview.png
  Lyricz finder/index.css
  Lyricz finder/index.html
  Lyricz finder/index.js
  Lyricz finder/preview.png
  Meditation feature/preview.png
  Picture Puzzle Game/preview.png
  Reflex Training/preview.png
  Screen distance Measure/preview.png
  Special number checker/preview.png
  Spotify Clone/preview.png
  SpotifyClone/preview.png
  Spy Number Checker/preview.png
  Sum Of Digits Caluclator/preview.png
  style_links.json
Labels: GSSoC22

#646 Color Picker
  Color Picker/index.html
  Color Picker/preview1.jpg
  Color Picker/script.js
  Color Picker/style.css
  style_links.json
Labels: GSSoC22

#651 ADD: Emoji-Search
  Emoji-Search/emojis.json
  Emoji-Search/index.html
  Emoji-Search/index.js
  Emoji-Search/preview.png
  Emoji-Search/style.css
  style_links.json
Labels: Level2, GSSoC22

#672 Improved Magic color website
  Magic Color/index.html
Labels: Level1, GSSoC22, ready to merge

#628 Simple Library Management
  Simple Libray Management/images/SimpleLibraryManagement(mobile).png
  Simple Libray Management/images/SimpleLibraryManagement.png
  Simple Libray Management/index.html
  Simple Libray Management/preview.png
  Simple Libray Management/readme.md
  Simple Libray Management/script.js
  ___images/2048.png
  ___images/BaseX Calculator (1).png
  ___images/Color Flipper __ Simple.png
  ___images/Document.png
  ___images/Don't Let The Ball Down (1).png
  ___images/Expense Tracker App.png
  ___images/Flipbook.png
  ___images/Gradient Background.png
  ___images/Image Resizer.png
  ___images/Music Website.png
  ___images/Picture in Picture.png
  ___images/Pokemon Card Generator.png
  ___images/Quote Generator.png
  ___images/Random Jokes Generator.png
  ___images/Random color generator.png
  ___images/Stopwatch.png
  ___images/Sudoku.png
  ___images/Text to Speech Converter.png
  ___images/Up Counter.png
  ___images/Youtube Music.png
  style_links.json
Labels: GSSoC22, ready to merge

#635 Password-generator project added
  Random Password Generator/index.html
  Random Password Generator/preview.png
  Random Password Generator/script.js
  Random Password Generator/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#650 Added Circular Timer
  Circular Timer/index.html
  Circular Timer/script.js
  Circular Timer/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#680 Improved BaseX calculator
  BaseX_Calculator/index.html
  BaseX_Calculator/preview.png
  BaseX_Calculator/style.css
Labels: Level2, GSSoC22, ready to merge

#678 Improved UI of Quote Generator
  Quote Generator/bg.jpg
  Quote Generator/css/bootstrap-grid.css
  Quote Generator/css/bootstrap-grid.css.map
  Quote Generator/css/bootstrap-grid.min.css
  Quote Generator/css/bootstrap-grid.min.css.map
  Quote Generator/css/bootstrap-reboot.css
  Quote Generator/css/bootstrap-reboot.css.map
  Quote Generator/css/bootstrap-reboot.min.css
  Quote Generator/css/bootstrap-reboot.min.css.map
  Quote Generator/css/bootstrap.css
  Quote Generator/css/bootstrap.css.map
  Quote Generator/css/bootstrap.min.css
  Quote Generator/css/bootstrap.min.css.map
  Quote Generator/index.html
  Quote Generator/preview.png
  Quote Generator/style.css
Labels: GSSoC22, ready to merge

#683 Random Color Generator
  Color Generator/index.html
  Color Generator/index.js
  Color Generator/preview.png
  Color Generator/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#693 Fix: issue 664
  Special number checker/index.html
  Special number checker/preview.png
  Special number checker/special.css
  Special number checker/special.js
Labels: Level2, GSSoC22, ready to merge

#684 add-burger-menu
  Burger-Menu/css/mobile.css
  Burger-Menu/css/style.css
  Burger-Menu/index.html
  Burger-Menu/preview.png
  Burger-Menu/scripts/script.js
  Burger-Menu/static/background.jpg
  Burger-Menu/static/close.svg
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#691 FIX: issue668 and "click on january is buggy"
  Clock And Alarm/calendar.css
  Clock And Alarm/index.html
  Clock And Alarm/js/alarm.js
  Clock And Alarm/js/calendar.js
  Clock And Alarm/js/clock.js
  Clock And Alarm/style.css
Labels: Level2, GSSoC22, ready to merge

#692 Fix: Issue665
  Analog clock/index.html
  Analog clock/main.css
  Analog clock/main.js
Labels: Level2, GSSoC22, ready to merge

#696 Solved issue #667 . Made Bubble Burst Game responsive and increase the size of bubbles
  Bubble Burst Game/index.html
  Bubble Burst Game/script.js
Labels: Level1, GSSoC22, ready to merge

#699 Fix: issue 694
  Circular Timer/preview.png
  Color Checker/preview.png
  Color Picker/preview.png
  Color Picker/preview1.jpg
  Feedback slider/preview.png
  Photo-Editor/preview.png
  Pomodoro-Timer/preview.png
  Simple Library Management/images/SimpleLibraryManagement(mobile).png
  Simple Library Management/images/SimpleLibraryManagement.png
  Simple Library Management/index.html
  Simple Library Management/preview.png
  Simple Library Management/readme.md
  Simple Library Management/script.js
  Spin-and-Win-Game/preview.png
  ToDo App/preview.png
  color-guessing game/index.html
  color-guessing game/javascript/main.js
  index.html
  script.js
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#702 Fix: issue 674 add WordCountTool
  style_links.json
  wordCountTool/index.html
  wordCountTool/index.js
  wordCountTool/preview.png
  wordCountTool/style.css
Labels: Level2, GSSoC22, ready to merge

#704 #700 Bug fixed
  index.html
  script.js
Labels: GSSoC22, ready to merge, Level0

#706 Added Custom QR Code Generator
  Custom QR Code/assets/favicon.png
  Custom QR Code/assets/img.png
  Custom QR Code/font/sans.ttf
  Custom QR Code/index.html
  Custom QR Code/preview.png
  Custom QR Code/script.js
  Custom QR Code/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#711 Completely fixed the responsiveness of the slider from Feedback Slider
  Feedback slider/index.html
  Feedback slider/script.js
  Feedback slider/style.css
Labels: Level2, GSSoC22, ready to merge

#709 Fixed Errors - Refactored Images and Added Fallback
  Fortune Cookie Generator/index.html
  calculatorspage.html
  index.html
  logo.png
  script.js
  style.css
Labels: GSSoC22, ready to merge

#714 Added BankingMoneyTranfer
  BankingMoneyTranfer/icon.png
  BankingMoneyTranfer/index.html
  BankingMoneyTranfer/logo.png
  BankingMoneyTranfer/preview.png
  BankingMoneyTranfer/readme.md.txt
  BankingMoneyTranfer/script.js
  BankingMoneyTranfer/style.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#721 Sorted The Repo Alphabetically and Removing Duplicate Project
  2D Snake Game/preview.png
  Alarm_Clock/preview.png
  BankingMoneyTranfer/preview.png
  Digital_Clock/preview.png
  Flappy_Bird_clone/preview.png
  Function_Grapher/preview.png
  Live User Filter/preview.png
  Quiz/preview.png
  Random Wave/preview.png
  Stopwatch (minimalist)/preview.png
  Tic-Tac-Toe with 2 player/preview.png
  Typer/preview.png
  Typewriter effect/preview.png
  custom Emoji slider/preview.png
  number_system_convertor/index.html
  number_system_convertor/preview.png
  piano/preview.png
  style_links.json
Labels: Level3, GSSoC22, ready to merge
